import Foundation

// MARK: - Lossless Concat Join (Wave 2, task 2.5)

/// DJI MP4 segments are self-contained, so joining is a container re-mux with the elementary
/// streams copied byte-for-byte — FFmpeg's **concat demuxer** with `-c copy`. There is no BMX
/// rewrap stage (that was P2-only and has been dropped).
///
/// The argument/list construction is split into **pure** static builders (no process, no
/// bundle, no I/O — directly unit-testable) and a thin `mergeClips(...)` that writes the list
/// file and drives `runFFmpeg`.
extension FFmpegWrapper {

    /// Output-side metadata stamped onto the joined file during the join. Populated by
    /// `QueueManager.resolveJoinMetadata` (task 2.8) from the group's resolved recording-start
    /// wall-clock (`RecordingStartResolver`): `creationTime` is the ISO-8601 instant, `timecode`
    /// the derived `HH:MM:SS:FF` start. Both stay optional — either toggle off, or no signal
    /// resolves, leaves a field `nil` and the builder simply omits that flag.
    struct JoinMetadata: Equatable {
        /// `creation_time` value in a form FFmpeg accepts (ISO-8601, e.g.
        /// `2023-08-13T10:20:11.000000Z`). Written via `-metadata creation_time=…`.
        var creationTime: String?
        /// Start timecode `HH:MM:SS:FF` for the output `tmcd` track. Written via `-timecode`.
        var timecode: String?

        init(creationTime: String? = nil, timecode: String? = nil) {
            self.creationTime = creationTime
            self.timecode = timecode
        }
    }

    /// What `mergeClips` does with each segment's in-container data stream(s).
    enum DataStreamPolicy: Equatable, Sendable {
        /// Today's DJI behaviour, unchanged since 1.0.4: `-map -0:d` drops every data stream.
        case drop
        /// GoPro: resolve the gpmd telemetry stream's absolute index at join time and map it
        /// explicitly (`buildMergeArguments`'s `gpmdStreamIndex` branch).
        case preserveTelemetry
    }

    // MARK: - Pure builders (unit-testable)

    /// Builds the concat-demuxer list-file body for an ordered set of segment URLs.
    ///
    /// Each line is `file '<absolute-path>'`. Embedded single quotes are escaped using FFmpeg's
    /// `'\''` convention so paths with apostrophes are handled. The trailing newline is included.
    static func buildConcatList(for segments: [URL]) -> String {
        segments
            .map { "file '\(concatEscape($0.path))'" }
            .joined(separator: "\n") + "\n"
    }

    /// Builds the full FFmpeg argument vector for a lossless concat join.
    ///
    /// Shape (matches the spec / `CLAUDE.md`), `gpmdStreamIndex == nil` (DJI, unchanged since 1.0.4):
    /// ```
    /// -f concat -safe 0 -i <list> -map 0:v:0 -map 0:a? -map -0:d -c copy \
    ///   -fflags +genpts -movflags +faststart [-metadata creation_time=…] [-timecode …] -y <out>
    /// ```
    /// - `-map 0:v:0` keeps **only the primary** video stream. DJI MP4s embed a second, low-res
    ///   mjpeg *preview* track (`v:1`); a bare `-map 0:v` would carry it into the joined master,
    ///   where the concat copy mangles it into a malformed 3-frame stream (real-footage finding,
    ///   2026-06). `-map 0:a?` keeps audio when present; `-map -0:d` drops DJI's in-container data
    ///   (telemetry) tracks that would otherwise break `-c copy`.
    /// - `-fflags +genpts` regenerates a clean PTS across the seam; `+faststart` moves the moov
    ///   atom to the front for progressive playback.
    ///
    /// Shape when `gpmdStreamIndex` is supplied (GoPro):
    /// ```
    /// -f concat -safe 0 -i <list> -map 0:v:0 -map 0:a? -map 0:<i> -c copy -copy_unknown \
    ///   -fflags +genpts -movflags +faststart [-metadata creation_time=…] [-timecode …] -y <out>
    /// ```
    /// - A bare `-map 0` is a hard failure on GoPro sources — ffmpeg errors "Could not find tag
    ///   for codec none in stream #2" and leaves a zero-byte output — so every stream is mapped
    ///   explicitly.
    /// - The gpmd telemetry stream is not at a fixed position (measured index 3 in a Hero 11
    ///   original with audio, index 2 in a no-audio original, index 2 in a remux), so `i` is
    ///   always a caller-supplied probed absolute stream index — never `d:0`, since ffprobe
    ///   reports the `tmcd` timecode track as `codec_type=data` too and `d:0` can silently
    ///   resolve to it instead. `-map -0:d` is dropped in this shape: the explicit `-map 0:<i>`
    ///   already selects the one data stream to keep. `-copy_unknown` is required for the gpmd
    ///   stream to survive the copy. The `tmcd` timecode track is deliberately left unmapped —
    ///   it is regenerated by the `-timecode` flag below.
    static func buildMergeArguments(
        listFileURL: URL,
        outputURL: URL,
        metadata: JoinMetadata = JoinMetadata(),
        gpmdStreamIndex: Int? = nil
    ) -> [String] {
        var args: [String] = [
            "-f", "concat",
            "-safe", "0",
            "-i", listFileURL.path,
            "-map", "0:v:0",
            "-map", "0:a?",
        ]

        if let gpmdStreamIndex {
            args.append(contentsOf: ["-map", "0:\(gpmdStreamIndex)"])
            args.append(contentsOf: ["-c", "copy"])
            args.append("-copy_unknown")
        } else {
            args.append(contentsOf: ["-map", "-0:d"])
            args.append(contentsOf: ["-c", "copy"])
        }

        args.append(contentsOf: [
            "-fflags", "+genpts",
            "-movflags", "+faststart",
        ])

        if let creationTime = metadata.creationTime {
            args.append(contentsOf: ["-metadata", "creation_time=\(creationTime)"])
        }
        if let timecode = metadata.timecode {
            args.append(contentsOf: ["-timecode", timecode])
        }

        args.append(contentsOf: ["-y", outputURL.path])
        return args
    }

    /// Resolves the gpmd telemetry stream's absolute index for a `.preserveTelemetry` join from
    /// each segment's probed `SegmentStreamInfo`, in segment order (`infos[0]` / `segmentNames[0]`
    /// is segment 1). Refuses with `FFmpegError.dataStreamLayoutMismatch` if any segment's gpmd
    /// presence disagrees with segment 1's — a later segment recorded without telemetry (or vice
    /// versa) would otherwise map an index that doesn't mean the same thing in that file, silently
    /// dropping or corrupting the joined stream.
    ///
    /// Segment 1's index is the one returned: the concat demuxer presents *segment 1's* stream
    /// layout to the output, so `-map 0:<i>` is positional into that file specifically (see
    /// `buildMergeArguments`'s doc comment). This is a pure comparison — no process, no I/O — so
    /// the refusal path is unit-testable against synthetic `SegmentStreamInfo` values.
    static func resolveGpmdStreamIndex(
        for infos: [StreamParameterGuard.SegmentStreamInfo],
        segmentNames: [String]
    ) throws -> Int? {
        guard let reference = infos.first else { return nil }
        let referenceHasGpmd = reference.dataStreamIndex != nil

        for (offset, info) in infos.enumerated().dropFirst() {
            let hasGpmd = info.dataStreamIndex != nil
            guard hasGpmd == referenceHasGpmd else {
                let name = offset < segmentNames.count ? segmentNames[offset] : "segment \(offset + 1)"
                let (got, expected) = hasGpmd
                    ? ("has a gpmd stream", "no gpmd stream")
                    : ("has no gpmd stream", "a gpmd stream")
                throw FFmpegError.dataStreamLayoutMismatch(
                    "segment \(offset + 1) (\(name)) \(got), expected \(expected) (from segment 1)"
                )
            }
        }
        return reference.dataStreamIndex
    }

    /// Escapes a filesystem path for a concat-demuxer `file '…'` directive: a literal single
    /// quote becomes `'\''` (close-quote, escaped quote, re-open-quote).
    static func concatEscape(_ path: String) -> String {
        path.replacingOccurrences(of: "'", with: "'\\''")
    }

    // MARK: - Execution

    /// Joins ordered DJI segments into a single lossless file.
    ///
    /// Writes a temporary concat list, runs the join, and removes the list afterward. The caller
    /// is responsible for grouping (segments must share codec/res/fps — the param guard, task
    /// 2.6, lands in this path next) and for supplying `totalFrames` for accurate progress.
    ///
    /// **Single-file export:** a lone segment is the degenerate N=1 case — the concat demuxer
    /// copies its streams byte-for-byte, drops the mjpeg preview / data tracks, runs `+faststart`,
    /// and stamps the resolved `creation_time`/`tmcd`. The param guard is skipped (nothing to
    /// compare against), so a single clip can be re-exported purely to fix its date/timecode.
    /// - Parameters:
    ///   - segments: Ordered segment URLs (already validated as a contiguous group). One segment
    ///     is a valid single-file export.
    ///   - outputURL: Destination for the joined file.
    ///   - metadata: Optional `creation_time` / start timecode to stamp on the output.
    ///   - dataStreamPolicy: `.drop` (default) reproduces the 1.0.4 DJI vector exactly — no
    ///     probing beyond the existing param guard. `.preserveTelemetry` (GoPro) probes segment 1
    ///     at join time to resolve the gpmd stream's absolute index and refuses up front if any
    ///     segment's gpmd presence disagrees with segment 1's.
    ///   - totalFrames: Optional combined frame count for progress estimation.
    ///   - verifyParameters: When true (default), runs the stream-parameter guard (task 2.6)
    ///     and refuses the `-c copy` join if the segments' codec/res/fps/timebase/audio differ.
    func mergeClips(
        _ segments: [URL],
        to outputURL: URL,
        metadata: JoinMetadata = JoinMetadata(),
        dataStreamPolicy: DataStreamPolicy = .drop,
        totalFrames: Int? = nil,
        verifyParameters: Bool = true,
        progress: @escaping ProgressHandler,
        logHandler: @escaping LogHandler = { _ in },
        metricsHandler: MetricsHandler? = nil
    ) async throws {
        resetCancellation()

        guard let ffmpeg = ffmpegPath else {
            logHandler("ERROR: FFmpeg not found!")
            throw FFmpegError.ffmpegNotFound
        }
        guard segments.count >= 1 else {
            throw FFmpegError.invalidInput("Nothing to export (no segments)")
        }
        let isSingle = segments.count == 1

        progress(0.0, isSingle ? "Preparing export…" : "Preparing join…")

        // Pre-join parameter guard (task 2.6): refuse a lossless copy of mismatched streams.
        // Skipped for a single-file export — there is nothing to compare against.
        if verifyParameters && !isSingle {
            progress(0.05, "Verifying segment compatibility…")
            try ensureJoinable(segments, logHandler: logHandler)
        }

        // GoPro: resolve the gpmd stream's absolute index fresh at join time, from segment 1's
        // probed layout — never from a clip's persisted `streamInfo.dataStreamIndex`, which is a
        // grouping/verification signal only. Skipped entirely under `.drop`, so the DJI path never
        // pays for a probe it doesn't need.
        var gpmdStreamIndex: Int? = nil
        if dataStreamPolicy == .preserveTelemetry {
            let infos = try segments.map { try probeStreamInfo($0) }
            gpmdStreamIndex = try Self.resolveGpmdStreamIndex(
                for: infos,
                segmentNames: segments.map(\.lastPathComponent)
            )
        }

        // Write the concat list to a temp file (TempDirectoryManager lands in Wave 1.5).
        let listFileURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("conjoyn-concat-\(UUID().uuidString).txt")
        let listBody = Self.buildConcatList(for: segments)
        try listBody.write(to: listFileURL, atomically: true, encoding: .utf8)
        defer { try? FileManager.default.removeItem(at: listFileURL) }

        let args = Self.buildMergeArguments(
            listFileURL: listFileURL,
            outputURL: outputURL,
            metadata: metadata,
            gpmdStreamIndex: gpmdStreamIndex
        )
        logHandler("Command: ffmpeg " + args.joined(separator: " "))
        logHandler(isSingle
            ? "Exporting single file → \(outputURL.lastPathComponent)"
            : "Joining \(segments.count) segments → \(outputURL.lastPathComponent)")

        progress(0.1, "Starting FFmpeg…")
        try await runFFmpeg(
            at: ffmpeg,
            arguments: args,
            totalFrames: totalFrames,
            progress: progress,
            logHandler: logHandler,
            metricsHandler: metricsHandler
        )
        progress(1.0, isSingle ? "Export complete" : "Join complete")
    }
}
